name: Remove old artifacts

on:
  push:
    branches: [main]
  schedule:
    # Every day at 1am
    - cron: '45 22 * * ?'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest

    steps:
    - name: Remove artifacts
      uses: c-hive/gha-remove-artifacts@v1.2.0
      with:
        age: '10 minutes'
        # Optional inputs
        # skip-tags: true
        # skip-recent: 5
